import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>MMM</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-gray-300 to-gray-100">
        <Navbar />
      </main>
    </>
  );
};

export default Home;
