import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Registrar from "../components/Registrar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MMM</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-gray-300 to-gray-100">
        <Navbar />
        
        <h1 className="text-center text-2xl font-medium mt-2">Bienvenido al Registro para el Congreso mundial</h1>
        <Registrar />
      </main>
    </>
  );
};

export default Home;
